### Create Admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "serviceNumber": "na/2000", 
    "password": "password"
}

### test the healt of the server
GET http://localhost:5000/api/admin/health
Content-Type: application/json

### Create change password
POST http://localhost:5000/api/auth/change-password
Content-Type: application/json

{
    "serviceNumber": "na/2000", 
    "password": "password"
}