// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env["DATABASE_URL"] || "postgresql://postgres.nzxjjmkgwsblivxityqy:PwtQrBnf5aXYivfa@aws-1-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
    directUrl: env["DIRECT_URL"] || "postgresql://postgres:PwtQrBnf5aXYivfa@db.nzxjjmkgwsblivxityqy.supabase.co:5432/postgres",
  },
});
